<div id="embeddable_wrapper">
            <h2>Embeddable</h2>
            <div id="embeddable">
                <div id="code"></div>
            </div>
            <div id="processing" style="display:none;">
                <div class="style">
                &lt;style type="text/css"&gt;
                    div#BLOGATWEET { background:white; border:2px solid black; padding:4px; }
                    div#BLOGATWEET div.tweets div.tweet { cursor:pointer; overflow:auto; position:relative; }
                    div#BLOGATWEET div.tweets div.tweet:hover { background:#EFEFEF; }
                    div#BLOGATWEET div.tweets div.tweet div.image { float:left; width:48px; }
                    div#BLOGATWEET div.tweets div.tweet div.image img { height:48px; width:48px; }
                    div#BLOGATWEET div.tweets div.tweet div.text { margin-left:58px; }
                    div#BLOGATWEET div.tweets div.tweet div.text span.timedate { font-size:10px; }
                &lt;/style&gt;
                </div>
                <div class="tweets"></div>
            </div>
</div>
